CREATE TABLE perfil(
	nome VARCHAR(5) PRIMARY KEY
);

ALTER TABLE usuario	ADD COLUMN perfil VARCHAR(5) NOT NULL REFERENCES perfil(nome);

ALTER TABLE atleta ALTER COLUMN usuario_email TYPE VARCHAR(100);

INSERT INTO perfil VALUES('ADMIN');
INSERT INTO perfil VALUES('USER');