CREATE TABLE foto(
	id SERIAL PRIMARY KEY,
	original BYTEA NOT NULL,
	arquivo BYTEA NOT NULL,
	thumbnail BYTEA NOT NULL,
	extensao VARCHAR(4) NOT NULL
);

ALTER TABLE atleta	DROP COLUMN foto;
ALTER TABLE atleta	ADD COLUMN foto_id INTEGER REFERENCES foto(id);
